services:

  server:
    image: bqat-stateless:latest
    build: 
      context: .
      # args:
      #   - VER_CORE=value
      #   - VER_API=value
    shm_size: 8gb
    ports:
      - 8848:8848
    environment:
      DEBUG_MODE: YES
    volumes:
      - ./api:/app/api
      - ./bqat:/app/bqat
      - ./tests:/app/tests
    # command:
    #   - uvicorn api.app:app --host 0.0.0.0 --port 8848 --workers 8
