version: '3.9'

services:

  server:
    image: docker.io/library/bqat-stateless
    build: .
    shm_size: 8gb
    ports:
      - 8848:8848
    environment:
      DEBUG_MODE: YES
    volumes:
      - ./api:/app/api
      - ./bqat:/app/bqat
      - ./tests:/app/tests
